import { Task } from "@/types/task";
import { create } from "zustand";

const mockinitData: Task[] = [
  {
    taskId: "1",
    taskName: "Task 1",
    taskColor: "#FDACAC",
    taskDescription: "Task 1 description",
    totalTime: 10000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "2",
    taskName: "Task 2",
    taskColor: "#FFCDC9",
    taskDescription: "Task 2 description",
    totalTime: 20000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "3",
    taskName: "Task 3",
    taskColor: "#FD7979",
    taskDescription: "Task 3 description",
    totalTime: 30000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "4",
    taskName: "Task 4",
    taskColor: "#FF9B9B",
    taskDescription: "Task 4 description",
    totalTime: 15000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "5",
    taskName: "Task 5",
    taskColor: "#FFBAB8",
    taskDescription: "Task 5 description",
    totalTime: 25000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "6",
    taskName: "Task 6",
    taskColor: "#FD9F9F",
    taskDescription: "Task 6 description",
    totalTime: 18000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "7",
    taskName: "Task 7",
    taskColor: "#FFB5B0",
    taskDescription: "Task 7 description",
    totalTime: 22000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "8",
    taskName: "Task 8",
    taskColor: "#FF8A8A",
    taskDescription: "Task 8 description",
    totalTime: 12000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "9",
    taskName: "Task 9",
    taskColor: "#FFAAA5",
    taskDescription: "Task 9 description",
    totalTime: 28000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "10",
    taskName: "Task 10",
    taskColor: "#FD8F8F",
    taskDescription: "Task 10 description",
    totalTime: 16000,
    completedTime: 0,
    record: [],
  },
  {
    taskId: "11",
    taskName: "Task 11",
    taskColor: "#FFA7A0",
    taskDescription: "Task 11 description",
    totalTime: 24000,
    completedTime: 0,
    record: [],
  },
];

export const useTasksStore = create<{ tasks: Task[] }>()((set) => ({
  tasks: mockinitData,
}));
